# -*- coding: utf-8 -*-
"""Assignment 2 Muhammad Tayyab Sial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1se1AemITjj8BG6JYFv2xQEWqa_g9wms5

## **Part 1: NumPy Array Manipulation (The Core Data)**

**1. Product Data:**
"""

import numpy as np

# 1D array of product IDs
product_ids = np.array([1001, 1002, 1003, 1004, 1005,
                         1006, 1007, 1008, 1009, 1010])

# 2D array: [Current Stock, Avg Weekly Sales, Unit Cost]
inventory_data = np.array([
    [50,  15.5, 10.99],
    [120,  3.2, 50.50],
    [30,  25.0,  5.00],
    [80,  12.3,  8.75],
    [60,   7.8, 20.00],
    [45,  18.2,  6.50],
    [90,   9.4, 12.00],
    [20,  30.1,  4.25],
    [110,  5.6, 15.75],
    [70,  14.0,  9.99]
])

"""**2. Basic Calculations and Attributes:**"""

print("Shape:", inventory_data.shape)
print("Data type:", inventory_data.dtype)

total_value = inventory_data[:, 0] * inventory_data[:, 2]
print("Total value of current stock for each product:")
print(total_value)

"""**3. Slicing, Indexing, and Statistics:**


"""

products_3_to_7 = inventory_data[2:7]
print("Data for products 3 through 7:")
print(products_3_to_7)

average_weekly_sales_mean = np.mean(inventory_data[:, 1])
print("Average of Average Weekly Sales:", average_weekly_sales_mean)

unit_cost_first_product = inventory_data[0, 2]
print("Unit cost of first product:", unit_cost_first_product)

"""## **Part 2: Advanced NumPy Analysis (Re-stocking Logic)**

**1. Boolean Masking (The "Low-Stock" Check):**
"""

# Weeks of stock = current stock / avg weekly sales
weeks_of_stock = inventory_data[:, 0] / inventory_data[:, 1]

print("\nWeeks of stock:\n", weeks_of_stock)

# Boolean mask: less than 4 weeks
low_stock_mask = weeks_of_stock < 4

print("\nLow stock mask:\n", low_stock_mask)

# Extract low-stock products
low_stock_products = inventory_data[low_stock_mask]

print("\nProducts with less than 4 weeks of stock:\n", low_stock_products)

"""**2. Reshaping and Concatenation (Updating Data):**"""

# Reorder quantity to reach 4-week supply
reorder_quantity = (4 * inventory_data[:, 1]) - inventory_data[:, 0]

# Ensure non-negative values
reorder_quantity = np.maximum(reorder_quantity, 0)

print("\nReorder quantity:\n", reorder_quantity)

# Reshape to (10, 1)
reorder_quantity = reorder_quantity.reshape(-1, 1)

# Concatenate with inventory_data
updated_inventory_data = np.concatenate(
    (inventory_data, reorder_quantity),
    axis=1
)
print("\nUpdated inventory data (Stock, Sales, Cost, Reorder Qty):\n")
print(updated_inventory_data)

"""## **Part 3: Introduction to Pandas (Viewing the Results)**

**1. Create a DataFrame:**
"""

import pandas as pd

# Create DataFrame
df = pd.DataFrame(
    updated_inventory_data,
    columns=['Stock', 'Sales', 'Cost', 'Reorder Qty']
)

"""**2. Basic Selection:**"""

print("Inventory DataFrame:\n")
print(df)

print("\nStock and Reorder Quantity:\n")
print(df[['Stock', 'Reorder Qty']])

print("\nFirst 5 rows of the DataFrame:\n")
print(df.head(5))

