# -*- coding: utf-8 -*-
"""Muhammad_Tayyab_Sial_Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odhHvV2qGsRDguLHY_zq6H-IBTpdXaEa

**Part 1: The Student Class (OOP and Data Structures)**
"""

class Student:
    def __init__(self, name, student_id, courses_and_grades):
        # If courses_and_grades is a tuple list → convert to dictionary
        if isinstance(courses_and_grades, list) and all(isinstance(x, tuple) for x in courses_and_grades):
            self.courses_and_grades = dict(courses_and_grades)
        else:
            self.courses_and_grades = courses_and_grades
        self.name = name
        self.student_id = student_id
        #self.courses_and_grades = courses_and_grades

    def get_average_grade(self):
        if not self.courses_and_grades:
            return 0
        total = sum(self.courses_and_grades.values())
        count = len(self.courses_and_grades)
        return total / count

    def add_course_and_grade(self, course_name, grade):
        self.courses_and_grades[course_name] = grade

    def get_honors_courses(self, threshold=90):
        honors = []
        for course, grade in self.courses_and_grades.items():
            if grade >= threshold:
                honors.append(course)
        return honors

    def get_unique_grades(self):
        return set(self.courses_and_grades.values())

    def __repr__(self):
        return f"Student(name={self.name}, student_id={self.student_id}, courses={self.courses_and_grades})"

obj_stu = Student('tayyab','314613',{'Math': 85, 'Science': 92, 'History': 78}) # Object initilization

obj_stu.get_average_grade()

obj_stu.add_course_and_grade('English',56)

obj_stu.get_honors_courses()

obj_stu.get_unique_grades()

"""**Part 2: The Manager Logic (Sequence Functions and Control Flow)**"""

all_students = []

# Student 1
s1 = Student("Ali", 101, {"Math": 85, "Science": 92, "History": 78})

# Student 2 — tuple list
s2 = Student("Sara", 102, [("Art", 95), ("PE", 88), ("English", 91)])

s3 = Student("John", 103, {"Biology": 60, "Chemistry": 72, "Math": 70})

# Add to list
all_students.extend([s1, s2, s3])

s2.get_average_grade() #test if tuple is converted to dictionary

for student in all_students:
    avg = student.get_average_grade()

    if avg > 80:
        honors = student.get_honors_courses()
        print(f"{student.name} has an excellent average of {avg:.2f} and the following honor courses: {honors}")
    else:
        # Add new course for low performers
        student.add_course_and_grade("Study Skills", 100)
        print(f"{student.name}'s average was {avg:.2f}. Added 'Study Skills' with grade 100.")